from ml.targets.build import (
get_target_names,
)

from ml.targets.common import (
DAILY_HORIZONS,
PERIOD_HORIZONS,
)

# ==========================================================

# TARGET TASK DEFINITIONS

# ==========================================================

#

# IMPORTANT:

#

# The Target Builder is the single source of truth for

# generated target names and horizons.

#

# This registry only defines the TASK TYPE of each target

# family:

#

# regression

# classification

# categorical

#

# Target names themselves are generated from the current

# horizon definitions.

# ==========================================================

# ==========================================================

# TARGET FAMILIES

# ==========================================================

REGRESSION_TARGET_FAMILIES = {
    'Target_Expense_Total',
    'Target_Income_Total',
    'Target_Balance',
    'Target_Expense_Days',
    'Target_Income_Days',
}

BINARY_CLASSIFICATION_TARGET_FAMILIES = {
# Activity
'Target_Has_Activity',
'Target_High_Activity',
'Target_Long_Activity',


# Behavioral
'Target_High_Stress',
'Target_Moderate_or_High_Stress',
'Target_Low_Sleep',
'Target_Very_Low_Sleep',
'Target_High_Social_Activity',
'Target_Moderate_or_High_Social_Activity',
'Target_Working_Day',
'Target_Difficult_Behavioral_Day',

# Events
'Target_Has_Event',
'Target_Multiple_Events',
'Target_Has_Special_Event',

# Health
'Target_Health_Problem',
'Target_High_Health_Severity',
'Target_Low_Energy',
'Target_Significant_Health_Day',

# Location
'Target_Has_Location',
'Target_Location_Changed',
'Target_Same_Location',

# Patterns
'Target_High_Expense',
'Target_Busy_Day',
'Target_Financial_Activity',
'Target_Difficult_Day',
'Target_Active_Day',
'Target_Travel_Day',
'Target_Special_Day',


}

CATEGORICAL_TARGET_FAMILIES = {
'Target_Location',
}

# ==========================================================

# HORIZON HELPERS

# ==========================================================

def _get_all_horizons():
    """
    Return every horizon currently generated by the
    Target Builder.

    ```
    The order is deterministic and follows the project
    horizon definitions.
    """

    return (
        list(DAILY_HORIZONS)
        + list(PERIOD_HORIZONS)
    )


def _target_family(target_name):
    """
    Extract the target family from a generated target name.

    Example:

        Target_Expense_Total_1D
        ->
        Target_Expense_Total
    """

    for horizon in _get_all_horizons():

        suffix = f'_{horizon}'

        if target_name.endswith(suffix):

            return target_name[
                :-len(suffix)
            ]

    return None


def _build_family_targets(families):
    """
    Generate all concrete target names for the supplied
    target families using the current horizon definitions.
    """

    targets = set()

    for family in families:

        for horizon in _get_all_horizons():

            targets.add(
                f'{family}_{horizon}'
            )

    return targets


# ==========================================================

# CONCRETE TARGET REGISTRY

# ==========================================================

REGRESSION_TARGETS = _build_family_targets(
REGRESSION_TARGET_FAMILIES
)

BINARY_CLASSIFICATION_TARGETS = (
_build_family_targets(
BINARY_CLASSIFICATION_TARGET_FAMILIES
)
)

CATEGORICAL_TARGETS = _build_family_targets(
CATEGORICAL_TARGET_FAMILIES
)

# ==========================================================

# VALIDATION

# ==========================================================

def validate_target_registry():
    """
    Validate that the target registry exactly matches the
    targets generated by the Target Builder.

    ```
    Checks:

        1. No generated target is missing.
        2. No registry target is unknown.
        3. No target belongs to multiple task groups.
        4. Every generated target has a known task type.
    """

    generated_targets = set(
        get_target_names()
    )

    registry_targets = (
        REGRESSION_TARGETS
        | BINARY_CLASSIFICATION_TARGETS
        | CATEGORICAL_TARGETS
    )

# ------------------------------------------------------
# Generated targets missing from registry
# ------------------------------------------------------

    missing = (
        generated_targets
        - registry_targets
    )

    if missing:

        raise ValueError(
            'Targets missing from registry: '
            f'{sorted(missing)}'
        )

    # ------------------------------------------------------
    # Registry targets that are not generated
    # ------------------------------------------------------

    unknown = (
        registry_targets
        - generated_targets
    )

    if unknown:

        raise ValueError(
            'Registry contains unknown targets: '
            f'{sorted(unknown)}'
        )

# ------------------------------------------------------
# Check overlaps
# ------------------------------------------------------

    groups = [
        REGRESSION_TARGETS,
        BINARY_CLASSIFICATION_TARGETS,
        CATEGORICAL_TARGETS,
    ]

    overlaps = []

    for index, first in enumerate(groups):

        for second in groups[index + 1:]:

            overlaps.extend(
                first & second
            )

    if overlaps:

        raise ValueError(
            'Targets appear in multiple registry groups: '
            f'{sorted(set(overlaps))}'
        )

    # ------------------------------------------------------
    # Check that every generated target has a family
    # ------------------------------------------------------

    unresolved = []

    for target_name in generated_targets:

        family = _target_family(
            target_name
        )

        if family is None:

            unresolved.append(
                target_name
            )

    if unresolved:

        raise ValueError(
            'Unable to determine target family for: '
            f'{sorted(unresolved)}'
        )

# ------------------------------------------------------
# Check that every target belongs to exactly one family
# ------------------------------------------------------

    family_sets = [
        REGRESSION_TARGET_FAMILIES,
        BINARY_CLASSIFICATION_TARGET_FAMILIES,
        CATEGORICAL_TARGET_FAMILIES,
    ]

    for target_name in generated_targets:

        family = _target_family(
            target_name
        )

        matches = sum(
            family in family_set
            for family_set in family_sets
        )

        if matches != 1:

            raise ValueError(
                'Target family has invalid task assignment: '
                f'{target_name}'
            )

    return True


# ==========================================================

# TARGET TASK

# ==========================================================

def get_target_task(
target_name,
):
    """
    Return the machine-learning task type for a target.

    Returns:

        regression
        classification
        categorical
    """

    validate_target_registry()

    if target_name in REGRESSION_TARGETS:

        return 'regression'

    if target_name in BINARY_CLASSIFICATION_TARGETS:

        return 'classification'

    if target_name in CATEGORICAL_TARGETS:

        return 'categorical'

    raise ValueError(
        f'Unknown target: {target_name}'
    )


# ==========================================================

# PUBLIC HELPERS

# ==========================================================

def is_regression_target(
target_name,
):
    """
    Return True when target is a regression target.
    """

    
    return (
        get_target_task(
            target_name
        )
        == 'regression'
    )
    

def is_classification_target(
    target_name,
    ):
    """
    Return True when target is a binary classification
    target.
    """

    return (
        get_target_task(
            target_name
        )
        == 'classification'
    )


def is_categorical_target(target_name,):
    """
    Return True when target is a categorical target.
    """

    return (
        get_target_task(
            target_name
        )
        == 'categorical'
    )

# ==========================================================

# REGISTRY SUMMARY

# ==========================================================

def get_registry_summary():
    """
    Return a compact summary of the target registry.
    """

    validate_target_registry()

    return {
        'total_targets': (
            len(REGRESSION_TARGETS)
            + len(BINARY_CLASSIFICATION_TARGETS)
            + len(CATEGORICAL_TARGETS)
        ),

        'regression_targets':
            len(REGRESSION_TARGETS),

        'classification_targets':
            len(BINARY_CLASSIFICATION_TARGETS),

        'categorical_targets':
            len(CATEGORICAL_TARGETS),

        'daily_horizons':
            list(DAILY_HORIZONS),

        'period_horizons':
            list(PERIOD_HORIZONS),
    }


    # ==========================================================

    # SIMPLE TEST

    # ==========================================================

if __name__ == '__main__':


        print()
        print(
            '========== TARGET REGISTRY TEST =========='
        )

        validate_target_registry()

        print(
            'Registry completeness: PASSED'
        )

        summary = get_registry_summary()

        print()
        print(
            'Total targets:',
            summary['total_targets']
        )

        print(
            'Regression targets:',
            summary['regression_targets']
        )

        print(
            'Classification targets:',
            summary['classification_targets']
        )

        print(
            'Categorical targets:',
            summary['categorical_targets']
        )

        print()
        print(
            'Daily horizons:',
            summary['daily_horizons']
        )

        print(
            'Period horizons:',
            summary['period_horizons']
        )

        print()
        print(
            'Expense target:',
            get_target_task(
                'Target_Expense_Total_1D'
            )
        )

        print(
            'Working-day target:',
            get_target_task(
                'Target_Working_Day_1D'
            )
        )

        print(
            'Location target:',
            get_target_task(
                'Target_Location_1D'
            )
        )

        print()
        print(
            '========== TARGET REGISTRY TEST PASSED =========='
        )
